CSV Sorting
hunterachieng/python-cmd-agency-app pull request #1
Opened 2022-05-23 12:44 UTC by hunterachieng

2022-05-25 16:32 UTC, lakivisi reviewed
- add a gitignore file and ignore the pyc files
- Can you create it as a cli app using click or docopt

2022-05-25 16:38 UTC, lakivisi requested changes

2022-05-25 16:38 UTC, lakivisi commented on main.py
>  with open('real-estate-sample.csv', 'r') as file:
this is repetitive you can create a function that takes in file name and mode and updates accordingly

2022-05-25 17:40 UTC, hunterachieng commented
I shall update it to a cli app

On Wed, 25 May 2022, 19:38 Lakivisi, ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In main.py
> <https://github.com/hunterachieng/python-cmd-agency-app/pull/1#discussion_r881884066>
> :
>
> > @@ -3,6 +3,14 @@
>  data = []
>  with open('real-estate-sample.csv', 'r') as file:
>
> this is repetitive you can create a function that takes in file name and
> mode and updates accordingly
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/hunterachieng/python-cmd-agency-app/pull/1#pullrequestreview-985151871>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AS4KQNT2JBXVX7XU57QUIV3VLZJPXANCNFSM5WVXKXRQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-05-30 20:31 UTC, lakivisi requested changes
Good progress on the click

2022-05-30 20:31 UTC, lakivisi commented on venv/cmd_project/scripts/command_line.py
> +    sorted = MergeSort(data)
Separate this out. Have the function just do a simple thing. The read or write functions should not depend on the sort

2022-05-30 20:31 UTC, lakivisi commented on venv/cmd_project/scripts/command_line.py
> +@click.command()
Yes this is a correct usage of click

2022-06-11 07:54 UTC, merged